# -*- coding: utf-8 -*-
"""pdfreader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mxddsDZgJX-BoPjBYCYClE135zWuRdqj
"""

# !pip  install PyPDF2
# importing required modules
import PyPDF2

filename1 = 'example.pdf'
filename2 = 'example2.pdf'
# creating a pdf file object
pdfFileObj = open(filename1, 'rb') # the first param of open is the file path as of now its relative to the code, but in case u have to give whole dir path
pdfFileObj2 = open(filename2, 'rb')
 
# creating a pdf reader object
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
pdfReader2 = PyPDF2.PdfFileReader(pdfFileObj2)
 
# printing number of pages in pdf file
# print(pdfReader.numPages)
 
# creating a page object
pageObj = pdfReader.getPage(0)
pageObj2 = pdfReader2.getPage(0)
 
# extracting text from page
pdf1 = pageObj.extractText()
pdf1 = pdf1.lower()

#cleaning the code
pdf2 = pageObj2.extractText()
pdf2 = pdf2.lower()
pdf2 = pdf2.split('!')

# closing the pdf file object
pdfFileObj.close()
pdfFileObj2.close()

#logic code
print(pdf2)
print(pdf1)
foundWords = list()
for word in pdf2:
  if word in pdf1:
    foundWords.append(word)
print('{} -- {}'.format(filename1, ', '.join(foundWords)))

import pandas as pd

df = pd.DataFrame(columns=['File name', 'Found word'])
df = df.append({'File name': filename1, 'Found word': foundWords}, ignore_index = True)
# for word in foundWords:
#   df = df.append({'File name': filename1, 'Found word': word}, ignore_index = True)


#saving the xlsx file
df.to_excel('result.xlsx', index=False)